application: findit-for-me-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: default
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_concurrent_requests: 25

builtins:
  - remote_api: on

handlers:
# Static resources and home page.
- url: /
  static_files: templates/home.html
  upload: templates/home.html

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /common.css
  static_files: static/common.css
  upload: static/common.css

# Pipeline status UI handler.
- url: /_ah/pipeline(/.*)?
  script: main.pipeline_status_application
  secure: always

# Endpoints handler.
- url: /_ah/spi/.*
  script: main.api_application
  secure: always

- url: /.*
  script: main.default_web_application
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*_test\.py$
- ^(.*/)?tests\.py$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
- ^(.*/)?README$
- ^(.*/)?Makefile$
- ^(.*/)?util_scripts/.*$

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
